language: node_js
node_js:
  - "9"
dist: trusty
addons:
  chrome: stable
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm run test-headless
after_failure:
  - cat /home/travis/.npm/_logs/*-debug.log
